name: morningstar
description: Call of Duty Mobile game database.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.1
  cached_network_image: ^3.2.0
  darq: ^1.1.1
  device_info_plus: ^3.2.1
  devicelocale: ^0.5.0
  enum_to_string: ^2.0.1
  flutter_bloc: ^7.3.1
  flutter_colorpicker: ^1.0.3
  flutter_inappwebview: ^5.3.2
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.9
  flutter_native_timezone: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_user_agentx: ^1.2.4
  fluttertoast: ^8.0.8
  freezed_annotation: ^0.15.0
  get_it: ^7.2.0
  grouped_list: ^4.1.0
  google_fonts: ^2.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  image_gallery_saver: ^1.7.1
  infinite_listview: ^1.1.0
  internet_connection_checker: ^0.0.1+3
  intl_utils: ^2.6.1
  json_annotation: ^4.4.0
  logger: ^1.1.0
  minio: ^3.5.0
  package_info_plus: ^1.3.0
  path: ^1.8.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  pull_to_refresh: ^2.0.0
  rate_my_app: ^1.1.1+1
  responsive_builder: ^0.4.1
  responsive_grid: ^2.0.0
  screenshot: ^1.2.3
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  sprintf: ^6.0.0
  synchronized: ^3.0.0
  transparent_image: ^2.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.18
  version_tracker: ^2.1.1
  waterfall_flow: ^3.0.2
  webview_windows: ^0.1.5
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size


  cupertino_icons: ^1.0.4

dev_dependencies:
  bloc_test: ^8.4.0
  build_runner:
  flutter_launcher_icons: ^0.9.2
  freezed: ^0.15.0+1
  hive_generator: ^1.1.2
  json_serializable: ^6.1.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  msix: ^2.8.3

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/items/logos/app_icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/db/
    - assets/cosmetics/
    - assets/weapons/
    - assets/weapons/primary/
    - assets/weapons/secondary/
    - assets/weapons/throwable/
    - assets/i18n/
    - assets/elements/
    - assets/items/logos/
    - assets/items/others/
    - assets/videos/
    - assets/gif/
    - assets/items/logos/app_icon.png


  fonts:
    - family: MorningstarFont
      fonts:
        - asset: assets/fonts/MorningstarFont.ttf

flutter_intl:
  enabled: true
