/// Flutter icons MorningstarFont
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MorningstarFont
///      fonts:
///       - asset: fonts/MorningstarFont.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class MorningstarFont {
  MorningstarFont._();

  static const _kFontFam = 'MorningstarFont';
  static const String? _kFontPkg = null;

  static const IconData bat_sword = IconData(0xe91b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData croc_sword = IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dervish_swords = IconData(0xe990, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinning_sword = IconData(0xeab3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venomous_snake = IconData(0xeadf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xf1b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf35f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData truck_monster = IconData(0xf63b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
